export const GET_BITCOIN_DATA_PENDING = 'GET_BITCOIN_DATA_PENDING';
export const GET_BITCOIN_DATA_SUCCESS = 'GET_BITCOIN_DATA_SUCCESS';
export const GET_BITCOIN_DATA_ERROR = 'GET_BITCOIN_DATA_ERROR';
