export const GET_COINS_PENDING = 'GET_COINS_PENDING';
export const GET_COINS_SUCCESS = 'GET_COINS_SUCCESS';
export const GET_COINS_ERROR = 'GET_COINS_ERROR';
export const GET_MORE_COINS_PENDING = 'GET_MORE_COINS_PENDING';
export const GET_MORE_COINS_SUCCESS = 'GET_MORE_COINS_SUCCESS';
export const GET_MORE_COINS_ERROR = 'GET_MORE_COINS_ERROR';